openapi: 3.0.1
info:
  title: User Microservice API
  version: 1.0.0
  description: API REST para gerenciamento de usuários
servers:
  - url: http://localhost:8081/api
paths:
  /users:
    get:
      summary: Lista todos os usuários
      responses:
        '200':
          description: Lista de usuários
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserDTO'
    post:
      summary: Cria um novo usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDTO'
      responses:
        '201':
          description: Usuário criado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDTO'
        '400':
          description: Erro de validação ou e-mail duplicado
  /users/{id}:
    get:
      summary: Busca um usuário pelo ID
      parameters:
        - in: path
          name: id
          required: true
          description: ID do usuário
          schema:
            type: integer
      responses:
        '200':
          description: Usuário encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDTO'
        '404':
          description: Usuário não encontrado
    put:
      summary: Atualiza um usuário existente
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDTO'
      responses:
        '200':
          description: Usuário atualizado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDTO'
        '404':
          description: Usuário não encontrado
    delete:
      summary: Deleta um usuário
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Usuário deletado com sucesso
        '404':
          description: Usuário não encontrado
components:
  schemas:
    UserDTO:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: João da Silva
        email:
          type: string
          example: joao@email.com